<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'code' => 'LAP-001',
                'name' => 'Lápiz HB Pelikan',
                'description' => 'Lápiz de grafito HB, mina resistente',
                'category' => 'Escritura',
                'unit_price' => 1500,
                'cost' => 800,
                'stock' => 500,
                'min_stock' => 50,
                'is_active' => true,
            ],
            [
                'code' => 'CUA-001',
                'name' => 'Cuaderno Norma 100 Hojas',
                'description' => 'Cuaderno cuadriculado 100 hojas tamaño carta',
                'category' => 'Cuadernos',
                'unit_price' => 8500,
                'cost' => 5200,
                'stock' => 200,
                'min_stock' => 30,
                'is_active' => true,
            ],
            [
                'code' => 'BOL-001',
                'name' => 'Bolígrafo Bic Azul',
                'description' => 'Bolígrafo de tinta azul, trazo fino',
                'category' => 'Escritura',
                'unit_price' => 2000,
                'cost' => 1100,
                'stock' => 800,
                'min_stock' => 100,
                'is_active' => true,
            ],
            [
                'code' => 'RES-001',
                'name' => 'Resma Papel Bond Carta',
                'description' => 'Resma de 500 hojas papel bond carta 75g',
                'category' => 'Papel',
                'unit_price' => 15000,
                'cost' => 10500,
                'stock' => 150,
                'min_stock' => 20,
                'is_active' => true,
            ],
            [
                'code' => 'CAR-001',
                'name' => 'Carpeta Legajadora Oficio',
                'description' => 'Carpeta legajadora tamaño oficio con gancho',
                'category' => 'Archivo',
                'unit_price' => 4500,
                'cost' => 2800,
                'stock' => 300,
                'min_stock' => 40,
                'is_active' => true,
            ],
            [
                'code' => 'MAR-001',
                'name' => 'Marcador Sharpie Negro',
                'description' => 'Marcador permanente punta fina negro',
                'category' => 'Escritura',
                'unit_price' => 5500,
                'cost' => 3500,
                'stock' => 250,
                'min_stock' => 30,
                'is_active' => true,
            ],
            [
                'code' => 'TIJ-001',
                'name' => 'Tijeras Escolares Maped',
                'description' => 'Tijeras punta roma 13cm para uso escolar',
                'category' => 'Herramientas',
                'unit_price' => 7000,
                'cost' => 4200,
                'stock' => 180,
                'min_stock' => 25,
                'is_active' => true,
            ],
            [
                'code' => 'PEG-001',
                'name' => 'Pegamento en Barra UHU',
                'description' => 'Pegamento en barra 21g no tóxico',
                'category' => 'Adhesivos',
                'unit_price' => 6000,
                'cost' => 3800,
                'stock' => 220,
                'min_stock' => 35,
                'is_active' => true,
            ],
            [
                'code' => 'BOR-001',
                'name' => 'Borrador Nata Pelikan',
                'description' => 'Borrador de nata blanco suave',
                'category' => 'Corrección',
                'unit_price' => 1800,
                'cost' => 900,
                'stock' => 400,
                'min_stock' => 60,
                'is_active' => true,
            ],
            [
                'code' => 'REG-001',
                'name' => 'Regla Metálica 30cm',
                'description' => 'Regla de aluminio graduada 30cm',
                'category' => 'Herramientas',
                'unit_price' => 5000,
                'cost' => 3000,
                'stock' => 150,
                'min_stock' => 20,
                'is_active' => true,
            ],
            [
                'code' => 'COL-001',
                'name' => 'Colores Norma x12',
                'description' => 'Caja de 12 colores de madera hexagonales',
                'category' => 'Arte',
                'unit_price' => 12000,
                'cost' => 7500,
                'stock' => 180,
                'min_stock' => 25,
                'is_active' => true,
            ],
            [
                'code' => 'CIN-001',
                'name' => 'Cinta Adhesiva Scotch',
                'description' => 'Cinta adhesiva transparente 18mm x 33m',
                'category' => 'Adhesivos',
                'unit_price' => 4500,
                'cost' => 2700,
                'stock' => 350,
                'min_stock' => 50,
                'is_active' => true,
            ],
            [
                'code' => 'COR-001',
                'name' => 'Corrector Líquido Paper Mate',
                'description' => 'Corrector líquido blanco 20ml secado rápido',
                'category' => 'Corrección',
                'unit_price' => 3500,
                'cost' => 2000,
                'stock' => 280,
                'min_stock' => 40,
                'is_active' => true,
            ],
            [
                'code' => 'TAJ-001',
                'name' => 'Tajador Metálico Doble',
                'description' => 'Tajador metálico con depósito doble orificio',
                'category' => 'Herramientas',
                'unit_price' => 3000,
                'cost' => 1800,
                'stock' => 320,
                'min_stock' => 45,
                'is_active' => true,
            ],
            [
                'code' => 'GRA-001',
                'name' => 'Grapadora Metalica',
                'description' => 'Grapadora metálica capacidad 20 hojas',
                'category' => 'Archivo',
                'unit_price' => 18000,
                'cost' => 12000,
                'stock' => 100,
                'min_stock' => 15,
                'is_active' => true,
            ],
            [
                'code' => 'POS-001',
                'name' => 'Post-it Amarillo 3x3',
                'description' => 'Notas adhesivas amarillas 76x76mm x100 hojas',
                'category' => 'Papel',
                'unit_price' => 8000,
                'cost' => 5000,
                'stock' => 200,
                'min_stock' => 30,
                'is_active' => true,
            ],
            [
                'code' => 'FLD-001',
                'name' => 'Folder Tamaño Carta',
                'description' => 'Folder de cartulina colores variados',
                'category' => 'Archivo',
                'unit_price' => 1000,
                'cost' => 500,
                'stock' => 600,
                'min_stock' => 80,
                'is_active' => true,
            ],
            [
                'code' => 'RES-002',
                'name' => 'Resaltador Stabilo Amarillo',
                'description' => 'Resaltador fluorescente amarillo trazo 2-5mm',
                'category' => 'Escritura',
                'unit_price' => 4000,
                'cost' => 2500,
                'stock' => 240,
                'min_stock' => 35,
                'is_active' => true,
            ],
            [
                'code' => 'PLA-001',
                'name' => 'Plastilina Norma x12',
                'description' => 'Set de 12 colores de plastilina no tóxica',
                'category' => 'Arte',
                'unit_price' => 10000,
                'cost' => 6500,
                'stock' => 120,
                'min_stock' => 20,
                'is_active' => true,
            ],
            [
                'code' => 'GAR-001',
                'name' => 'Ganchos Legajadores x50',
                'description' => 'Caja de 50 ganchos legajadores plásticos',
                'category' => 'Archivo',
                'unit_price' => 6500,
                'cost' => 4000,
                'stock' => 160,
                'min_stock' => 25,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
